version: '3'
services:
  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  camera:
    restart: unless-stopped
    build: 
      context: ./camera
      args:
        IMAGE: ubuntu
    volumes:
      - recordings:/var/output/dash
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - camera
    ports:
      - 1629:443
    volumes:
      - ./stream/index.html:/usr/share/nginx/html/index.html:ro
      - ./stream/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/nginx/privkey.pem:ro
      - recordings:/usr/share/nginx/html/dash:ro
  oauth:
    image: voucher/vouch-proxy
    volumes:
      - ./vouch.yml:/config/config.yml
      - users:/data

volumes:
  recordings:
  users:
