version: '3'
services:
  camera:
    image: misalcedo/picam
    restart: unless-stopped
    environment:
      PARAMETERS: resources/parameters.yaml
    ports:
      - 1629:443
    devices:
      - /dev/${DEVICE}
    volumes:
      - ${CERTS}/fullchain.pem:/usr/src/app/resources/fullchain.pem
      - ${CERTS}/privkey.pem:/usr/src/app/resources/privkey.pem
      - ./resources/parameters.yaml:/usr/src/app/resources/parameters.yaml
    depends_on:
      - redis
  watchtower:
    image: v2tec/watchtower:armhf-latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  redis:
    image: redis:alpine
    restart: unless-stopped
