version: '3'
services:
  camera:
    image: misalcedo/picam
    env_file: users.env
    restart: unless-stopped
    build:
      context: .
      args:
        opencv_version: 4.0.1
        port: 443
    ports:
      - 1629:443
    devices:
      - /dev/video0
    volumes:
      - ${CERTS}/fullchain.pem:/usr/src/app/fullchain.pem
      - ${CERTS}/privkey.pem:/usr/src/app/privkey.pem
      - .:/usr/src/app
  watchtower:
    image: v2tec/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
