version: '3'
services:
  pi:
    image: misalcedo/picam
    env_file: users.env
    restart: unless-stopped
    build:
      context: .
      args:
        opencv_version: 4.0.1
        port: 443
    ports:
      - 1629:443
    devices:
      - /dev/vchiq
    volumes:
      - /etc/letsencrypt/live/puppy-cam.salcedo.cc/fullchain.pem:/usr/src/app/fullchain.pem
      - /etc/letsencrypt/live/puppy-cam.salcedo.cc/privkey.pem:/usr/src/app/privkey.pem
      - .:/usr/src/app
  usb:
    image: misalcedo/picam
    env_file: users.env
    build:
      context: .
      args:
        opencv_version: 4.0.1
        port: 443
    ports:
      - 1629:443
    devices:
      - /dev/video0
    volumes:
      - .:/usr/src/app
