version: '3'
services:
  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  camera:
    image: ubuntu
    restart: unless-stopped
    build: 
      context: ./camera
    volumes:
      - recordings:/var/output/dash
    devices:
      - /dev/video0:/dev/video0
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./stream/index.html:/usr/share/nginx/html/index.html:ro
      - ./stream/nginx.conf:/etc/nginx/nginx.conf:ro
      - recordings:/usr/share/nginx/html/dash:ro
volumes:
  recordings:
