version: '3'
services:
  camera:
    image: misalcedo/picam
    restart: unless-stopped
    ports:
      - 1629:443
    devices:
      - /dev/${DEVICE}
    volumes:
      - ${CERTS}/fullchain.pem:/etc/picam/fullchain.pem
      - ${CERTS}/privkey.pem:/etc/picam/privkey.pem
      - ./resource/overrides.yml:/etc/picam/config.yml
    depends_on:
      - redis
  watchtower:
    image: v2tec/watchtower:armhf-latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  redis:
    image: redis:alpine
    restart: unless-stopped
