FROM resin/raspberrypi3-python:3-onbuild

EXPOSE 443

ARG domain
ARG camera

RUN apt-get update && apt-get upgrade -y

COPY requirements-pi.txt ./
RUN pip install --no-cache-dir -r requirements-pi.txt

ENV CAMERA=$camera DOMAIN=$domain

CMD python3 -u main.py --port 443 --camera $CAMERA --domain $DOMAIN --users $USERS
