FROM python:3-alpine

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-usb.txt ./
RUN pip install --no-cache-dir -r requirements-usb.txt

EXPOSE 443

ARG domain
ARG camera

ENV CAMERA=$camera DOMAIN=$domain

COPY . .

CMD python3 main.py --port 443 --camera $CAMERA --domain $DOMAIN