#!/usr/bin/env bash

modprobe bcm2835-v4l2

v4l2-ctl --set-fmt-video=width=1920,height=1080,pixelformat=4
v4l2-ctl --set-ctrl=rotate=$CAMERA_ROTATION
v4l2-ctl --overlay=1
v4l2-ctl -p 30
v4l2-ctl --set-ctrl=video_bitrate=4000000

ffmpeg -flags +genpts+igndts \
       -f h264 -framerate 30 -thread_queue_size 4096 -i /dev/video0 \
       -vcodec copy -flags +cgop -g 60 \
       -an \
       -f $STREAM_PROTOCOL $STREAM_URL
