#!/usr/bin/env bash

modprobe bcm2835-v4l2

v4l2-ctl --set-fmt-video=width=1920,height=1080,pixelformat=4
v4l2-ctl --set-ctrl=rotate=180
v4l2-ctl --overlay=1
v4l2-ctl -p 30
v4l2-ctl --set-ctrl=video_bitrate=4000000

ffmpeg -fflags +genpts+igndts \
       -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -i /dev/zero \
       -f h264 -framerate 30 -thread_queue_size 512 -i /dev/video0 \
       -vcodec copy -g 60 \
       -acodec aac -ab 128k \
       -f flv -r 30 rtmp://a.rtmp.youtube.com/live2/$YOUTUBE_STREAMING_KEY
