server:
  port: 443
  host: "0.0.0.0"
  chain: "resources/fullchain.pem"
  key: "resources/privkey.pem"
oauth:
  client_secret: "resources/client_secret.json"
camera:
  source: 0
  fps: 24
  orientation: 1
users:
