FROM python:3

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential cmake unzip pkg-config libjpeg-dev libpng-dev libtiff-dev \
        libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev \
        libx264-dev libgtk-3-dev libatlas-base-dev gfortran && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt

ARG opencv_version
ENV OPENCV_VERSION=$opencv_version

RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip && \
  wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip && \
  unzip opencv.zip && unzip opencv_contrib.zip && rm -rf opencv*.zip

WORKDIR /opt/opencv-${OPENCV_VERSION}/build

COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN cmake \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D BUILD_TESTS=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv_contrib-${OPENCV_VERSION}/modules \
  -D PYTHON_EXECUTABLE=$(which python3) \
  -D INSTALL_PYTHON_EXAMPLES=OFF \
  -D INSTALL_C_EXAMPLES=OFF \
  -D BUILD_EXAMPLES=OFF \
  .. && make -j12 && make install && \
  ldconfig && cd /opt && rm -fr /opt/opencv*

WORKDIR /usr/src/app

COPY . .

CMD python3 -u main.py
