version: '3'
services:
  watchtower:
    image: v2tec/watchtower:armhf-latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  feed:
    image: misalcedo/picam-feed
    restart: unless-stopped
    stop_grace_period: 1s
    build: 
      context: ./feed
    volumes:
      - recordings:/var/output/hls
  stream:
    image: misalcedo/picam-stream
    restart: unless-stopped
    build:
      context: ./stream
    depends_on:
      - feed
    ports:
      - 2916:80
    volumes:
      - recordings:/usr/share/nginx/html/hls:ro

volumes:
  recordings:
