version: '3'
services:
  feed:
    command: "-ar 48000 -ac 2 -f alsa -i hw:2,0 -f v4l2 -s hd1080 -input_format mjpeg -i /dev/video0 -vcodec libx264 -vprofile high422 -level '4.2' -preset ultrafast -tune zerolatency -g 30 -r 15 -acodec aac -ab 128k -f dash -min_seg_duration 2000 -remove_at_exit 1 -window_size 10 live.mpd"
