version: '3'
services:
  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - oauth
    ports:
      - 1629:443
    networks:
      - hub
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/nginx/privkey.pem:ro
      - recordings:/usr/share/nginx/html/dash:ro
  oauth:
    image: voucher/vouch-proxy
    networks:
      - hub
    volumes:
      - ./vouch.yml:/config/config.yml
      - users:/data

networks:
  hub:

volumes:
  recordings:
  users:
